# User Modeling

In [ ]:
import pandas as pd
from sklearn import datasets

users = pd.read_csv("resources/data/user_dataset.csv", encoding="utf-8")

In [13]:
users.head(10)

,user_no,user_id,user_gender,user_age,buy_count,cheese_rank,cheese_code,cheese_id,cheese_brand,cheese_name,cheese_texture,cheese_types,cheese_category,cheese_one_price,gender,age_group,cheese_category_code,cheese_texture_code,brand,brand_code
0,0,2391853,M,40,1,8.0,8,p8,프란시아,리코타 치즈,후레쉬치즈,자연치즈,리코타,"4,600원",0,3,3,1,프란시아,15
1,1,1799897,F,40,1,8.0,8,p8,프란시아,리코타 치즈,후레쉬치즈,자연치즈,리코타,"4,600원",1,3,3,1,프란시아,15
2,2,1614947,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30
3,3,1614947,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30
4,4,1614947,F,50,5,14.0,15,p14,콜롬보,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"4,900원",1,4,1,1,콜롬보,28
5,5,1614947,F,50,1,3.0,3,p3,브렐렛,모짜렐라 카우,후레쉬치즈,자연치즈,모짜렐라,"3,990원",1,4,1,1,브렐렛,12
6,6,6523993,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30
7,7,6523993,F,50,5,14.0,15,p14,콜롬보,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"4,900원",1,4,1,1,콜롬보,28
8,8,6523993,F,50,5,14.0,15,p14,콜롬보,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"4,900원",1,4,1,1,콜롬보,28
9,9,389215,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30

In [14]:
cheese.head(10)

,Unnamed: 0,ranking,cheese_id,brand,name,country,matching,texture,types,category,price,content,img,brand_code
0,1,1,1,벨지오이오소,부라타 치즈,이탈리아,"채소, 발사믹식초, 견과류",1,1,11,"14,900원",버터처럼 부드러운 크림이 들어있는 생치즈,https://img-cf.kurly.com/shop/data/goods/15153...,11
1,2,2,2,프란시아,모짜렐라 카우,이탈리아,"토마토,바질,샐러드",1,1,1,"3,870원",신선하게 피어난 우유 그대로의 맛,https://img-cf.kurly.com/shop/data/goods/15445...,15
2,3,3,3,브렐렛,모짜렐라 카우,이탈리아,"카프레제, 사퀘테리",1,1,1,"3,990원",이탈리아 브리미에서 제조된 신선한 모짜렐라!,https://img-cf.kurly.com/shop/data/goods/15464...,12
3,4,4,4,카스텔로,덴마크 브리 치즈,덴마크,"빵, 꿀, 견과류, 와인",4,1,8,"4,165원",부드럽게 녹아드는 숙성치즈의 매력,https://img-cf.kurly.com/shop/data/goods/15663...,32
4,5,5,5,브리미,보코치니,이탈리아,"샐러드, 올리브유",1,1,1,"6,800원",새알을 빚어놓은 듯 깜찍한 미니 모짜렐라,https://img-cf.kurly.com/shop/data/goods/15227...,34
5,6,6,6,무르젤라,이탈리아 부라타 120g,이탈리아,"빵, 샤퀴테리, 핑거푸드",1,1,11,"6,600원",정통 레시피를 고수한 이탈리아 부라타 치즈!,https://img-cf.kurly.com/shop/data/goods/15834...,40
6,7,7,7,오로비안코,부라타 치즈,이탈리아,"샐러드, 올리브오일, 발사믹식초,",1,1,11,"7,900원",진하고도 순수한 이탈리아의 풍미,https://img-cf.kurly.com/shop/data/goods/15481...,22
7,8,8,8,프란시아,리코타 치즈,이탈리아,"샐러드,크래커",1,1,3,"4,600원",매일매일 가볍고 신선하게,https://img-cf.kurly.com/shop/data/goods/15529...,15
8,9,9,9,zott,바질 모짜렐라 치즈,독일,"카프레제,파스타,피자",1,1,1,"4,600원",신선한 치즈와 향긋한 바질의 환상 궁합,https://img-cf.kurly.com/shop/data/goods/15266...,19
9,10,10,10,푸글리제,모짜렐라,이탈리아,"토마토,바질",1,1,1,"5,500원",담백하고 결이 살아있는 생 모짜렐라,https://img-cf.kurly.com/shop/data/goods/14872...,30

## 1. User Modeling - Random Forest

In [93]:
from sklearn.model_selection import train_test_split

X = users[['buy_count', 'cheese_rank', 'gender', 'age_group', 'cheese_texture_code', 'brand_code']]
y = users[['cheese_category_code']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [94]:
y.head(5)

   cheese_category_code
0                     3
1                     3
2                     1
3                     1
4                     1

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

forest = RandomForestClassifier(n_estimators=100)
forest.fit(x_train, y_train)

# 예측
y_pred = forest.predict(x_test)
print(y_pred)
# print(list(y_test))

print('정확도 : ', metrics.accuracy_score(y_test, y_pred))

print("특성 중요도: \n{}".format(forest.feature_importances_))

[1 1 1 ... 1 1 1]
정확도 :  0.4673657566443681
특성 중요도:
[0.39281508 0.19976629 0.05477487 0.18612311 0.0327603  0.13376035]

## 2. USer Modeling - SVM

In [40]:
# 특성 스케일링
# SVM을 훈련하기 전에 특성을 전처리해줘야 함. 각 특성마다 값의 범위에 차이가 있기 때문

x_train.describe()

,buy_count,cheese_rank,gender,age_group,cheese_texture_code,brand_code
count,25811.000000,25811.000000,25811.000000,25811.000000,25811.000000,25811.000000
mean,2.055868,10.930882,0.842896,2.498043,1.459804,20.120724
std,4.149733,11.135881,0.363905,0.843983,0.950113,10.621216
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
25%,1.000000,2.000000,1.000000,2.000000,1.000000,12.000000
50%,1.000000,7.000000,1.000000,2.000000,1.000000,15.000000
75%,2.000000,16.000000,1.000000,3.000000,1.000000,30.000000
max,160.000000,69.000000,1.000000,5.000000,6.000000,42.000000

In [52]:
import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate

# linear
clf = svm.SVC(kernel = 'linear')
clf.fit(X_train, y_train)

print("Displaying decision function.")

clf_predictions = clf.predict(X_test)
# print("정확도: {}%".format(clf.score(X_test, y_test) * 100))
print("정확도: {}%".format(clf.score(X_test, y_test)))

Displaying data.
Displaying decision function.
정확도: 0.6544928584342795%

In [57]:
# std 바꿔서 fitting

import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)

X_train_std = sc.transform(X_train)
print(X_train_std)
X_test_std = sc.transform(X_test)


# linear
clf = svm.SVC(kernel = 'linear')
clf.fit(X_train_std, y_train)


clf_predictions = clf.predict(X_test_std)
# print("정확도: {}%".format(clf.score(X_test, y_test) * 100))
print("정확도: {}%".format(clf.score(X_test, y_test)))

[[-0.25706587  0.18899892  0.4309656  -0.59472481 -0.48398416 -1.42392224]
 [-0.25706587  0.54830813  0.4309656  -0.59472481 -0.48398416 -0.48373987]
 [-0.25706587 -0.34996488  0.4309656   0.58944877 -0.48398416  0.17438778]
 ...
 [-0.25706587 -0.17031028  0.4309656   0.58944877 -0.48398416 -0.10766693]
 [-0.25706587  1.26692653 -2.32037081  1.77362236  1.60954948 -0.2957034 ]
 [-0.25706587  0.90761733  0.4309656   0.58944877 -0.48398416 -0.85981282]]
정확도: 0.07096365937443501%

# Cheese Modeling

In [136]:
cheese = pd.read_csv("resources/data/cheese_dataset.csv", encoding="utf-8")
cheese_matching = pd.read_csv("resources/data/cheese_matching.csv", encoding="utf-8")

In [137]:
cheese.head(5)

,Unnamed: 0,Unnamed: 0.1,ranking,cheese_id,brand,name,country,matching,texture,types,category,price,content,img,brand_code,country_code
0,0,1,1,1,벨지오이오소,부라타 치즈,이탈리아,"채소, 발사믹식초, 견과류",1,1,11,"14,900원",버터처럼 부드러운 크림이 들어있는 생치즈,https://img-cf.kurly.com/shop/data/goods/15153...,11,1
1,1,2,2,2,프란시아,모짜렐라 카우,이탈리아,"토마토,바질,샐러드",1,1,1,"3,870원",신선하게 피어난 우유 그대로의 맛,https://img-cf.kurly.com/shop/data/goods/15445...,15,1
2,2,3,3,3,브렐렛,모짜렐라 카우,이탈리아,"카프레제, 사퀘테리",1,1,1,"3,990원",이탈리아 브리미에서 제조된 신선한 모짜렐라!,https://img-cf.kurly.com/shop/data/goods/15464...,12,1
3,3,4,4,4,카스텔로,덴마크 브리 치즈,덴마크,"빵, 꿀, 견과류, 와인",4,1,8,"4,165원",부드럽게 녹아드는 숙성치즈의 매력,https://img-cf.kurly.com/shop/data/goods/15663...,32,7
4,4,5,5,5,브리미,보코치니,이탈리아,"샐러드, 올리브유",1,1,1,"6,800원",새알을 빚어놓은 듯 깜찍한 미니 모짜렐라,https://img-cf.kurly.com/shop/data/goods/15227...,34,1

In [138]:
cheese_df = cheese.rename(columns = {"Unnamed: 0": "cheese_no"})

In [139]:
cheese_df.head(5)

,cheese_no,Unnamed: 0.1,ranking,cheese_id,brand,name,country,matching,texture,types,category,price,content,img,brand_code,country_code
0,0,1,1,1,벨지오이오소,부라타 치즈,이탈리아,"채소, 발사믹식초, 견과류",1,1,11,"14,900원",버터처럼 부드러운 크림이 들어있는 생치즈,https://img-cf.kurly.com/shop/data/goods/15153...,11,1
1,1,2,2,2,프란시아,모짜렐라 카우,이탈리아,"토마토,바질,샐러드",1,1,1,"3,870원",신선하게 피어난 우유 그대로의 맛,https://img-cf.kurly.com/shop/data/goods/15445...,15,1
2,2,3,3,3,브렐렛,모짜렐라 카우,이탈리아,"카프레제, 사퀘테리",1,1,1,"3,990원",이탈리아 브리미에서 제조된 신선한 모짜렐라!,https://img-cf.kurly.com/shop/data/goods/15464...,12,1
3,3,4,4,4,카스텔로,덴마크 브리 치즈,덴마크,"빵, 꿀, 견과류, 와인",4,1,8,"4,165원",부드럽게 녹아드는 숙성치즈의 매력,https://img-cf.kurly.com/shop/data/goods/15663...,32,7
4,4,5,5,5,브리미,보코치니,이탈리아,"샐러드, 올리브유",1,1,1,"6,800원",새알을 빚어놓은 듯 깜찍한 미니 모짜렐라,https://img-cf.kurly.com/shop/data/goods/15227...,34,1

In [140]:
cheese_matching

,Unnamed: 0,간식,감자,견과류,과일,그라탕,김가루,꿀,딥소스,라자냐,...,테이블치즈,토마토,토스트,파스타,팬케이크,퐁듀,피자,핑거 푸드,핑거푸드,화이트와인
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
67,67,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
68,68,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69,69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
70,70,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [141]:
cheese_matching_df = cheese_matching.rename(columns={"Unnamed: 0": "cheese_no"})

In [142]:
cheese_matching_df

,cheese_no,간식,감자,견과류,과일,그라탕,김가루,꿀,딥소스,라자냐,...,테이블치즈,토마토,토스트,파스타,팬케이크,퐁듀,피자,핑거 푸드,핑거푸드,화이트와인
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
67,67,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
68,68,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69,69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
70,70,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [143]:
cheese_data = pd.merge(cheese_df, cheese_matching_df, on="cheese_no", how = "inner")

In [144]:
print(cheese_data.columns)

Index(['cheese_no', 'Unnamed: 0.1', 'ranking', 'cheese_id', 'brand', 'name',
       'country', 'matching', 'texture', 'types', 'category', 'price',
       'content', 'img', 'brand_code', 'country_code', '간식', '감자', '견과류', '과일',
       '그라탕', '김가루', '꿀', '딥소스', '라자냐', '리소토', '마르게리타 피자', '막걸리', '맥앤치즈', '맥주',
       '멤브리요', '무화과', '바질', '발사믹 식초', '발사믹식초', '배', '베이컨', '볶음밥', '비스킷', '빵',
       '사케', '사퀘테리', '샌드위치', '샐러드', '샐러리', '샤퀴테리', '소금', '스테이크', '스프', '스프레드',
       '올리브오일', '올리브유', '와인', '위스키', '잼', '채소', '치즈케이크', '카나페', '카프레제',
       '카프레제 샐러드', '크래커', '크로스티니', '키쉬', '타르트', '타파스', '테이블치즈', '토마토', '토스트',
       '파스타', '팬케이크', '퐁듀', '피자', '핑거 푸드', '핑거푸드', '화이트와인'],
      dtype='object')

In [145]:
cheese_all_data = cheese_data.drop(['Unnamed: 0.1', 'brand', 'country', 'matching', 'price', 'content', 'img'], axis=1)

In [146]:
cheese_all_data.columns

Index(['cheese_no', 'ranking', 'cheese_id', 'name', 'texture', 'types',
       'category', 'brand_code', 'country_code', '간식', '감자', '견과류', '과일',
       '그라탕', '김가루', '꿀', '딥소스', '라자냐', '리소토', '마르게리타 피자', '막걸리', '맥앤치즈', '맥주',
       '멤브리요', '무화과', '바질', '발사믹 식초', '발사믹식초', '배', '베이컨', '볶음밥', '비스킷', '빵',
       '사케', '사퀘테리', '샌드위치', '샐러드', '샐러리', '샤퀴테리', '소금', '스테이크', '스프', '스프레드',
       '올리브오일', '올리브유', '와인', '위스키', '잼', '채소', '치즈케이크', '카나페', '카프레제',
       '카프레제 샐러드', '크래커', '크로스티니', '키쉬', '타르트', '타파스', '테이블치즈', '토마토', '토스트',
       '파스타', '팬케이크', '퐁듀', '피자', '핑거 푸드', '핑거푸드', '화이트와인'],
      dtype='object')

In [147]:
cheese_all_data
cheese_all_data.to_csv("resources/data/cheese_final.csv", index=False, encoding='utf-8-sig')

## Split train, test

In [148]:
from sklearn.model_selection import train_test_split

# X = users.loc[['texture', 'types', 'category', 'brand_code', ]]
X = cheese_all_data.iloc[:, 4:68]
y = cheese_all_data['cheese_id']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [149]:
X_train

,texture,types,category,brand_code,country_code,간식,감자,견과류,과일,그라탕,...,테이블치즈,토마토,토스트,파스타,팬케이크,퐁듀,피자,핑거 푸드,핑거푸드,화이트와인
48,2,1,6,2,3,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
29,1,1,1,35,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,1,1,11,40,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,1,1,3,28,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
55,2,1,2,37,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
21,1,1,3,11,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,4,1,8,42,2,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
67,5,1,2,33,2,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
66,3,1,4,39,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2,1,2,7,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
51,1,1,1,34,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
20,1,1,1,11,2,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
23,1,1,3,34,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
69,3,1,9,4,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
45,3,1,5,23,1,0,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
6,1,1,11,22,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,3,1,9,4,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30,1,1,11,16,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,4,1,8,32,7,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
46,2,1,6,20,3,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
52,3,1,5,37,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
34,2,1,4,26,6,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
37,4,1,7,8,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
38,2,1,4,6,8,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
19,4,1,7,32,7,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
17,2,1,4,1,2,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
41,2,1,9,4,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,1,1,15,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
62,2,1,6,20,3,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
68,4,1,7,3,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,3,1,10,19,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60,2,1,4,39,2,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
42,4,1,8,36,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
0,1,1,11,11,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
35,4,1,8,8,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1,1,1,9,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,3,1,9,4,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
63,3,1,4,39,2,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22,3,1,10,14,2,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
54,3,1,5,23,1,0,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
65,5,1,2,21,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,1,1,1,25,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
25,3,1,5,23,1,0,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
61,2,1,2,13,2,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
33,3,1,5,17,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,1,1,1,19,5,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
7,1,1,3,15,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2,1,10,41,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2,1,1,1,2,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0

## 1. Cheese Modeling - Knn

In [150]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train, y_train)

print("정확도: {}%".format(classifier.score(X_test, y_test)))

In [153]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# sc = StandardScaler()
# sc.fit(X_train)

# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train, y_train)


prediction = classifier.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

report = classification_report(y_test, y_pre)
print(report)

ValueError: Found input variables with inconsistent numbers of samples: [22, 11062]

In [9]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans

import seaborn as sns
import matplotlib.pyplot as plt

sns.lmplot('category','ranking', data = cheese, fit_reg = False, scatter_kws = {"s":50})
#fit_reg = False는 회귀 옵션 제거, scatter_kws = {"s":50}는 산점도 그래프 점 크기 설정
plt.title('K-means Example')
plt.xlabel('category')
plt.ylabel('ranking')
plt.show()

cheese_df = cheese.values #numpy를 사용하기 위해 객체로 변환
kmeans = KMeans(n_clusters = 3).fit(cheese_df) #3개의 클러스트 발생
kmeans.cluster_centers_
kmeans.labels_

KeyError: "None of [Index(['category', 'ranking'], dtype='object')] are in the [columns]"