# User Modeling

In [1]:
import pandas as pd
from sklearn import datasets

users = pd.read_csv("resources/data/user_dataset.csv", encoding="utf-8")

In [13]:
users.head(10)

,user_no,user_id,user_gender,user_age,buy_count,cheese_rank,cheese_code,cheese_id,cheese_brand,cheese_name,cheese_texture,cheese_types,cheese_category,cheese_one_price,gender,age_group,cheese_category_code,cheese_texture_code,brand,brand_code
0,0,2391853,M,40,1,8.0,8,p8,프란시아,리코타 치즈,후레쉬치즈,자연치즈,리코타,"4,600원",0,3,3,1,프란시아,15
1,1,1799897,F,40,1,8.0,8,p8,프란시아,리코타 치즈,후레쉬치즈,자연치즈,리코타,"4,600원",1,3,3,1,프란시아,15
2,2,1614947,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30
3,3,1614947,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30
4,4,1614947,F,50,5,14.0,15,p14,콜롬보,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"4,900원",1,4,1,1,콜롬보,28
5,5,1614947,F,50,1,3.0,3,p3,브렐렛,모짜렐라 카우,후레쉬치즈,자연치즈,모짜렐라,"3,990원",1,4,1,1,브렐렛,12
6,6,6523993,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30
7,7,6523993,F,50,5,14.0,15,p14,콜롬보,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"4,900원",1,4,1,1,콜롬보,28
8,8,6523993,F,50,5,14.0,15,p14,콜롬보,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"4,900원",1,4,1,1,콜롬보,28
9,9,389215,F,50,1,10.0,10,p10,푸글리제,모짜렐라,후레쉬치즈,자연치즈,모짜렐라,"5,500원",1,4,1,1,푸글리제,30

In [14]:
cheese.head(10)

,Unnamed: 0,ranking,cheese_id,brand,name,country,matching,texture,types,category,price,content,img,brand_code
0,1,1,1,벨지오이오소,부라타 치즈,이탈리아,"채소, 발사믹식초, 견과류",1,1,11,"14,900원",버터처럼 부드러운 크림이 들어있는 생치즈,https://img-cf.kurly.com/shop/data/goods/15153...,11
1,2,2,2,프란시아,모짜렐라 카우,이탈리아,"토마토,바질,샐러드",1,1,1,"3,870원",신선하게 피어난 우유 그대로의 맛,https://img-cf.kurly.com/shop/data/goods/15445...,15
2,3,3,3,브렐렛,모짜렐라 카우,이탈리아,"카프레제, 사퀘테리",1,1,1,"3,990원",이탈리아 브리미에서 제조된 신선한 모짜렐라!,https://img-cf.kurly.com/shop/data/goods/15464...,12
3,4,4,4,카스텔로,덴마크 브리 치즈,덴마크,"빵, 꿀, 견과류, 와인",4,1,8,"4,165원",부드럽게 녹아드는 숙성치즈의 매력,https://img-cf.kurly.com/shop/data/goods/15663...,32
4,5,5,5,브리미,보코치니,이탈리아,"샐러드, 올리브유",1,1,1,"6,800원",새알을 빚어놓은 듯 깜찍한 미니 모짜렐라,https://img-cf.kurly.com/shop/data/goods/15227...,34
5,6,6,6,무르젤라,이탈리아 부라타 120g,이탈리아,"빵, 샤퀴테리, 핑거푸드",1,1,11,"6,600원",정통 레시피를 고수한 이탈리아 부라타 치즈!,https://img-cf.kurly.com/shop/data/goods/15834...,40
6,7,7,7,오로비안코,부라타 치즈,이탈리아,"샐러드, 올리브오일, 발사믹식초,",1,1,11,"7,900원",진하고도 순수한 이탈리아의 풍미,https://img-cf.kurly.com/shop/data/goods/15481...,22
7,8,8,8,프란시아,리코타 치즈,이탈리아,"샐러드,크래커",1,1,3,"4,600원",매일매일 가볍고 신선하게,https://img-cf.kurly.com/shop/data/goods/15529...,15
8,9,9,9,zott,바질 모짜렐라 치즈,독일,"카프레제,파스타,피자",1,1,1,"4,600원",신선한 치즈와 향긋한 바질의 환상 궁합,https://img-cf.kurly.com/shop/data/goods/15266...,19
9,10,10,10,푸글리제,모짜렐라,이탈리아,"토마토,바질",1,1,1,"5,500원",담백하고 결이 살아있는 생 모짜렐라,https://img-cf.kurly.com/shop/data/goods/14872...,30

In [2]:
from sklearn.model_selection import train_test_split

X = users[['buy_count', 'cheese_rank', 'gender', 'age_group', 'cheese_texture_code', 'brand_code']]
y = users[['cheese_category_code']]

X_user_train, X_user_test, y_user_train, y_user_test = train_test_split(X, y, test_size = 0.3)

## 1. User Modeling - Random Forest

In [50]:
y.head(5)

   cheese_category_code
0                     3
1                     3
2                     1
3                     1
4                     1

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_user_train, y_user_train)

# 예측
y_pred = forest.predict(X_user_test)
print(y_pred)
# print(list(y_test))

print('정확도 : ', metrics.accuracy_score(y_user_test, y_pred))

print("특성 중요도: \n{}".format(forest.feature_importances_))

<ipython-input-3-4a11ee9c2e46>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest.fit(X_user_train, y_user_train)

[11  3  1 ...  1  1  1]
정확도 :  0.9994576026035075
특성 중요도:
[0.00912545 0.55404766 0.00121619 0.00375165 0.19751148 0.23434757]

## 2. USer Modeling - SVM

In [40]:
# 특성 스케일링
# SVM을 훈련하기 전에 특성을 전처리해줘야 함. 각 특성마다 값의 범위에 차이가 있기 때문

x_train.describe()

,buy_count,cheese_rank,gender,age_group,cheese_texture_code,brand_code
count,25811.000000,25811.000000,25811.000000,25811.000000,25811.000000,25811.000000
mean,2.055868,10.930882,0.842896,2.498043,1.459804,20.120724
std,4.149733,11.135881,0.363905,0.843983,0.950113,10.621216
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
25%,1.000000,2.000000,1.000000,2.000000,1.000000,12.000000
50%,1.000000,7.000000,1.000000,2.000000,1.000000,15.000000
75%,2.000000,16.000000,1.000000,3.000000,1.000000,30.000000
max,160.000000,69.000000,1.000000,5.000000,6.000000,42.000000

In [16]:
import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate

# linear
clf = svm.SVC(kernel = 'linear')
clf.fit(X_user_train, y_user_train)

print("Displaying decision function.")

clf_predictions = clf.predict(X_user_test)
print("정확도: {}%".format(clf.score(X_user_test, y_user_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Displaying decision function.
정확도: 0.6525944675465558%

In [5]:
import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate

# linear
clf = svm.SVC(kernel = 'rbf')
clf.fit(X_user_train, y_user_train)

print("Displaying decision function.")

clf_predictions = clf.predict(X_user_test)
print("정확도: {}%".format(clf.score(X_user_test, y_user_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Displaying decision function.
정확도: 0.9140300126559393%

In [10]:
# std 바꿔서 fitting

import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler

# 표준화
std = StandardScaler()
# std.fit(X_train)

X_user_train_std = std.fit_transform(X_user_train)
X_user_test_std = std.transform(X_user_test)
print(X_user_train_std)

[[ 0.47005984 -0.88905726  0.43248133 -1.77039151 -0.48282954 -0.86093825]
 [-0.01765807 -0.88905726  0.43248133 -0.59057237 -0.48282954 -0.86093825]
 [-0.26151702 -0.79923596  0.43248133 -1.77039151 -0.48282954 -0.48336692]
 ...
 [-0.26151702 -0.61959335  0.43248133  0.58924678  2.65734683  1.1213112 ]
 [ 1.68935461  0.00915578  0.43248133 -0.59057237  0.56389592  1.97084668]
 [ 0.22620089  0.00915578 -2.31223853  0.58924678  0.56389592  1.97084668]]

In [8]:
from sklearn.preprocessing import MinMaxScaler

ns = MinMaxScaler()
ns.fit(X_user_train)

X_user_train_ns = ns.transform(X_user_train)
X_user_test_ns = ns.transform(X_user_test)
print(X_user_train_ns)

[[0.01886792 0.         1.         0.         0.         0.24390244]
 [0.00628931 0.         1.         0.25       0.         0.24390244]
 [0.         0.01470588 1.         0.         0.         0.34146341]
 ...
 [0.         0.04411765 1.         0.5        0.6        0.75609756]
 [0.05031447 0.14705882 1.         0.25       0.2        0.97560976]
 [0.01257862 0.14705882 0.         0.5        0.2        0.97560976]]

In [11]:
# 표준화
# linear
clf = svm.SVC(kernel = 'linear')
clf.fit(X_user_train_std, y_user_train)


clf_predictions = clf.predict(X_user_test_std)
print("정확도: {}%".format(clf.score(X_user_test_std, y_user_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

정확도: 0.6526848671126378%

In [15]:
# 정규화
# linear
clf = svm.SVC(kernel = 'linear')
clf.fit(X_user_train_ns, y_user_train)


clf_predictions = clf.predict(X_user_test_std)
print("정확도: {}%".format(clf.score(X_user_test_std, y_user_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

정확도: 0.4680889531730248%

# Cheese Modeling

In [3]:
import pandas as pd
cheese = pd.read_csv("resources/data/cheese_dataset.csv", encoding="utf-8")
cheese_matching = pd.read_csv("resources/data/cheese_matching.csv", encoding="utf-8")

In [4]:
cheese.head(5)

,Unnamed: 0,Unnamed: 0.1,ranking,cheese_id,brand,name,country,matching,texture,types,category,price,content,img
0,0,1,1,p1,벨지오이오소,부라타 치즈,이탈리아,"채소, 발사믹식초, 견과류",후레쉬치즈,자연치즈,부라타,14900,버터처럼 부드러운 크림이 들어있는 생치즈,https://img-cf.kurly.com/shop/data/goods/15153...
1,1,2,2,p2,프란시아,모짜렐라 카우,이탈리아,"토마토,바질,샐러드",후레쉬치즈,자연치즈,모짜렐라,3870,신선하게 피어난 우유 그대로의 맛,https://img-cf.kurly.com/shop/data/goods/15445...
2,2,3,3,p3,브렐렛,모짜렐라 카우,이탈리아,"카프레제, 사퀘테리",후레쉬치즈,자연치즈,모짜렐라,3990,이탈리아 브리미에서 제조된 신선한 모짜렐라!,https://img-cf.kurly.com/shop/data/goods/15464...
3,3,4,4,p4,카스텔로,덴마크 브리 치즈,덴마크,"빵, 꿀, 견과류, 와인",소프트치즈,자연치즈,브리,4165,부드럽게 녹아드는 숙성치즈의 매력,https://img-cf.kurly.com/shop/data/goods/15663...
4,4,5,5,p5,브리미,보코치니,이탈리아,"샐러드, 올리브유",후레쉬치즈,자연치즈,모짜렐라,6800,새알을 빚어놓은 듯 깜찍한 미니 모짜렐라,https://img-cf.kurly.com/shop/data/goods/15227...

In [5]:
cheese_df = cheese.rename(columns = {"Unnamed: 0": "cheese_no"})

In [6]:
cheese_df.head(5)

,cheese_no,Unnamed: 0.1,ranking,cheese_id,brand,name,country,matching,texture,types,category,price,content,img
0,0,1,1,p1,벨지오이오소,부라타 치즈,이탈리아,"채소, 발사믹식초, 견과류",후레쉬치즈,자연치즈,부라타,14900,버터처럼 부드러운 크림이 들어있는 생치즈,https://img-cf.kurly.com/shop/data/goods/15153...
1,1,2,2,p2,프란시아,모짜렐라 카우,이탈리아,"토마토,바질,샐러드",후레쉬치즈,자연치즈,모짜렐라,3870,신선하게 피어난 우유 그대로의 맛,https://img-cf.kurly.com/shop/data/goods/15445...
2,2,3,3,p3,브렐렛,모짜렐라 카우,이탈리아,"카프레제, 사퀘테리",후레쉬치즈,자연치즈,모짜렐라,3990,이탈리아 브리미에서 제조된 신선한 모짜렐라!,https://img-cf.kurly.com/shop/data/goods/15464...
3,3,4,4,p4,카스텔로,덴마크 브리 치즈,덴마크,"빵, 꿀, 견과류, 와인",소프트치즈,자연치즈,브리,4165,부드럽게 녹아드는 숙성치즈의 매력,https://img-cf.kurly.com/shop/data/goods/15663...
4,4,5,5,p5,브리미,보코치니,이탈리아,"샐러드, 올리브유",후레쉬치즈,자연치즈,모짜렐라,6800,새알을 빚어놓은 듯 깜찍한 미니 모짜렐라,https://img-cf.kurly.com/shop/data/goods/15227...

In [7]:
cheese_matching

,Unnamed: 0,간식,감자,견과류,과일,그라탕,김가루,꿀,딥소스,라자냐,...,테이블치즈,토마토,토스트,파스타,팬케이크,퐁듀,피자,핑거 푸드,핑거푸드,화이트와인
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
67,67,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
68,68,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69,69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
70,70,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [8]:
cheese_matching_df = cheese_matching.rename(columns={"Unnamed: 0": "cheese_no"})

In [9]:
cheese_matching_df

,cheese_no,간식,감자,견과류,과일,그라탕,김가루,꿀,딥소스,라자냐,...,테이블치즈,토마토,토스트,파스타,팬케이크,퐁듀,피자,핑거 푸드,핑거푸드,화이트와인
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
67,67,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
68,68,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69,69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
70,70,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [10]:
cheese_data = pd.merge(cheese_df, cheese_matching_df, on="cheese_no", how = "inner")

In [11]:
print(cheese_data.columns)

Index(['cheese_no', 'Unnamed: 0.1', 'ranking', 'cheese_id', 'brand', 'name',
       'country', 'matching', 'texture', 'types', 'category', 'price',
       'content', 'img', '간식', '감자', '견과류', '과일', '그라탕', '김가루', '꿀', '딥소스',
       '라자냐', '리소토', '마르게리타 피자', '막걸리', '맥앤치즈', '맥주', '멤브리요', '무화과', '바질',
       '발사믹 식초', '발사믹식초', '배', '베이컨', '볶음밥', '비스킷', '빵', '사케', '사퀘테리', '샌드위치',
       '샐러드', '샐러리', '샤퀴테리', '소금', '스테이크', '스프', '스프레드', '올리브오일', '올리브유', '와인',
       '위스키', '잼', '채소', '치즈케이크', '카나페', '카프레제', '카프레제 샐러드', '크래커', '크로스티니',
       '키쉬', '타르트', '타파스', '테이블치즈', '토마토', '토스트', '파스타', '팬케이크', '퐁듀', '피자',
       '핑거 푸드', '핑거푸드', '화이트와인'],
      dtype='object')

In [12]:
cheese_all_data = cheese_data.drop(['Unnamed: 0.1', 'brand', 'country', 'matching', 'price', 'content', 'img'], axis=1)

In [13]:
cheese_all_data.columns

Index(['cheese_no', 'ranking', 'cheese_id', 'name', 'texture', 'types',
       'category', '간식', '감자', '견과류', '과일', '그라탕', '김가루', '꿀', '딥소스', '라자냐',
       '리소토', '마르게리타 피자', '막걸리', '맥앤치즈', '맥주', '멤브리요', '무화과', '바질', '발사믹 식초',
       '발사믹식초', '배', '베이컨', '볶음밥', '비스킷', '빵', '사케', '사퀘테리', '샌드위치', '샐러드',
       '샐러리', '샤퀴테리', '소금', '스테이크', '스프', '스프레드', '올리브오일', '올리브유', '와인', '위스키',
       '잼', '채소', '치즈케이크', '카나페', '카프레제', '카프레제 샐러드', '크래커', '크로스티니', '키쉬',
       '타르트', '타파스', '테이블치즈', '토마토', '토스트', '파스타', '팬케이크', '퐁듀', '피자', '핑거 푸드',
       '핑거푸드', '화이트와인'],
      dtype='object')

In [14]:
cheese_all_data
cheese_all_data.to_csv("resources/data/cheese_final.csv", index=False, encoding='utf-8-sig')

In [15]:
import pandas as pd

cheese_all_data = pd.read_csv("resources/data/cheese_final.csv")

## Split train, test

In [16]:
from sklearn.model_selection import train_test_split

# X = users.loc[['texture', 'types', 'category', 'brand_code', ]]
X = cheese_all_data.iloc[:, 4:68]
X = X.drop(['category'], axis = 1)
y = cheese_all_data['category']

X_item_train, X_item_test, y_item_train, y_item_test = train_test_split(X, y, test_size = 0.3)

In [17]:
X.head(5)

,texture,types,간식,감자,견과류,과일,그라탕,김가루,꿀,딥소스,...,테이블치즈,토마토,토스트,파스타,팬케이크,퐁듀,피자,핑거 푸드,핑거푸드,화이트와인
0,후레쉬치즈,자연치즈,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,후레쉬치즈,자연치즈,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,후레쉬치즈,자연치즈,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,소프트치즈,자연치즈,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,후레쉬치즈,자연치즈,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 표준화

In [ ]:
# 정규화
def min_max_normalize(lst):
    
    normalized = []
    
    for value in lst:
        normalized_num = (value - min(lst)) / (max(lst) - min(lst))
        normalized.append(normalized_num)
        
    return normalized

for x in range(len(X.columns)):
    X_std = min_max_normalize(X[x])

X.describe()

In [ ]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler()
transformer.fit(X_item_train)
X_train_sc = transformer.transform(X_item_train)
transformer.fit(X_item_test)
X_test_sc = transformer.transform(X_item_test)
print(X_train_sc)

## 1. Cheese Modeling - Knn

In [150]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:

    @staticmethod
    def create_k_fold():
        return KFold(n_splits = 10, shuffle = True, random_state = 0)

    def accuracy_by_dtree(self, this):
        dtree = DecisionTreeClassifier()
        score = cross_val_score(dtree, this.train, this.label, cv = UserDf.create_k_fold(), \
                n_jobs = 1, scoring = 'accuracy')
        return round(np.mean(score) * 100, 2)

    def accuracy_by_rforest(self, this):
        rforest = RandomForestClassifier()
        score = cross_val_score(rforest, this.train, this.label, cv=UserDf.create_k_fold(), \
                n_jobs = 1, scoring = 'accuracy')
        return round(np.mean(score) * 100, 2)

    def accuracy_by_knn(self, this):
        knn = KNeighborsClassifier()
        score = cross_val_score(knn, this.train , this.label, cv = UserDf.create_k_fold(), \
                n_jobs = 1, scoring = 'accuracy')
        return round(np.mean(score) * 100, 2)

    def accuracy_by_svm(self, this):
        svm = SVC()
        score = cross_val_score(svm, this.train, this.label, cv = UserDf.create_k_fold(), \
                n_jobs = 1, scoring = 'accuracy')
        return round(np.mean(score) * 100, 2)
    
    def modeling(self, train, test):
        this = self.new(train, test)
        this.label = self.create_label(this)
        this.train = self.create_train(this)
        print(f'>> Train 변수 : {this.train.columns}')
        print(f'>> Test 변수 : {this.train.columns}')
        return this

    def learning(self, train, test):
        service = self.service
        this = self.modeling(train,test)
        print(f'Dtree verification result: {service.accuracy_by_dtree(this)}')
        print(f'RForest verification result: {service.accuracy_by_rforest(this)}')
        print(f'Naive Bayes tree verification result: {service.accuracy_by_nb(this)}')
        print(f'KNN verification result: {service.accuracy_by_knn(this)}')
        print(f'SVM verification result: {service.accuracy_by_svm(this)}')

In [45]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

clf = KNeighborsClassifier(n_neighbors = 3)
# clf = Pipeline([('norm', StandardScaler()), ('knn', clf)])

clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

0.3181818181818182

In [46]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

clf = KNeighborsClassifier(n_neighbors = 3)
# clf = Pipeline([('norm', StandardScaler()), ('knn', clf)])

clf.fit(X_train_sc, y_train)
print(clf.score(X_test_sc, y_test))

0.36363636363636365

In [34]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

clf = KNeighborsClassifier(n_neighbors = 3)
clf = Pipeline([('norm', StandardScaler()), ('knn', clf)])

kf = KFold(len(data), n_folds = 5, shuffle=True, random_state = 100)

ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [9]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans

import seaborn as sns
import matplotlib.pyplot as plt

sns.lmplot('category','ranking', data = cheese, fit_reg = False, scatter_kws = {"s":50})
#fit_reg = False는 회귀 옵션 제거, scatter_kws = {"s":50}는 산점도 그래프 점 크기 설정
plt.title('K-means Example')
plt.xlabel('category')
plt.ylabel('ranking')
plt.show()

cheese_df = cheese.values #numpy를 사용하기 위해 객체로 변환
kmeans = KMeans(n_clusters = 3).fit(cheese_df) #3개의 클러스트 발생
kmeans.cluster_centers_
kmeans.labels_

KeyError: "None of [Index(['category', 'ranking'], dtype='object')] are in the [columns]"